### ISSUE TITLE
Errors when running the run_experiments.ipynb notebook

### ISSUE THREAD

**Issue by ghost** [dh-r/LLM-Sequential-Recommendation#2]
Hello,

I am very interested in your work, but I have encountered several errors when running the notebook titled "run_experiments.ipynb", that I am hoping you can assist me on how to circumvent:

1 - When running the first cell of the notebook, a NameError appears saying name 'Dict' is not defined. This error is appearing due to importing the GRURec class from the main.grurec.grurec module. When changing 'Dict' to 'dict' within the GRURec class, the error no longer appears. But I would like to confirm that this change should be made or if this error should be fixed in another way.

2 - When running the SKNN model (6th cell of the notebook), a TypeError appears saying 'NoneType' object is not subscriptable.

3 - When running the BERT4Rec model (7th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/bert_weights is not a directory. The directory is there, however.

4 - When running the LLMTOBERT4Rec model (8th cell of the notebook), the following error appears: BadGzipFile: Not a gzipped file (b've').

5 - When running the GRU4Rec model (9th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/grurec_weights is not a directory. The directory is there, however.

6 - When running the SASRec model (10th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/sasrec_weights is not a directory. The directory is there, however.

Is there any way to fix these errors?

**Comment by zkotti** [comment]
Dear @ClaudiaFAfonso thank you for your comment! Please see our detailed response below.

> 1 - When running the first cell of the notebook, a NameError appears saying name 'Dict' is not defined. This error is appearing due to importing the GRURec class from the main.grurec.grurec module. When changing 'Dict' to 'dict' within the GRURec class, the error no longer appears. But I would like to confirm that this change should be made or if this error should be fixed in another way.

The issue was a missing import (see commit 94f3097) in `main/grurec/grurec.py`, which is now resolved. Please kindly note that you need to follow our `poetry` guidelines in our `README`, and use the correct `poetry` environment when running the notebook.

> 2 - When running the SKNN model (6th cell of the notebook), a TypeError appears saying 'NoneType' object is not subscriptable.
> 
> 3 - When running the BERT4Rec model (7th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/bert_weights is not a directory. The directory is there, however.
> 
> 5 - When running the GRU4Rec model (9th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/grurec_weights is not a directory. The directory is there, however.
> 
> 6 - When running the SASRec model (10th cell of the notebook), the following error appears: FailedPreconditionError: results/beauty/main/sasrec_weights is not a directory. The directory is there, however.

I could not reproduce the above errors. The cause could be the change you introduced in Question (1) together with the use of a wrong environment.

> 4 - When running the LLMTOBERT4Rec model (8th cell of the notebook), the following error appears: BadGzipFile: Not a gzipped file (b've').

The `beauty/product_embeddings_openai.csv.gzip` is stored with Git LFS, and should be manually downloaded from the top-level directory with `git lfs pull --include=beauty/product_embeddings_openai.csv.gzip`. We [clarified this](https://github.com/dh-r/LLM-Sequential-Recommendation/commit/cbdc5360e77aa84bbc84f3136fead2f021575bfd) in our `README`.
